name: Release JetBrains Plugin

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release-intellij:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        working-directory: ./jetbrains-plugin
        run: chmod +x gradlew

      - name: Build plugin
        working-directory: ./jetbrains-plugin
        run: ./gradlew buildPlugin

      - name: Get plugin artifact
        id: plugin
        working-directory: ./jetbrains-plugin
        run: |
          PLUGIN_PATH=$(find build/distributions -name "*.zip" -type f | head -1)
          echo "plugin-path=${PLUGIN_PATH}" >> $GITHUB_OUTPUT
          echo "plugin-name=$(basename ${PLUGIN_PATH})" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: jetbrains-plugin/${{ steps.plugin.outputs.plugin-path }}
          name: "JetBrains Plugin ${{ github.ref_name }}"
          body: |
            ## JetBrains Plugin Release ${{ github.ref_name }}
            
            ### Installation
            Download the `.zip` file and install it in your JetBrains IDE:
            1. Go to **File** → **Settings** → **Plugins**
            2. Click the gear icon and select **Install Plugin from Disk...**
            3. Choose the downloaded `.zip` file
            4. Restart your IDE
            
            ### Supported IDEs
            - IntelliJ IDEA (Community & Ultimate)
            - WebStorm, PyCharm, Android Studio
            - PhpStorm, CLion, RubyMine, DataGrip
            - Rider, GoLand, and other JetBrains IDEs
            
            ### Changes
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}